# Generated by Django 5.0.3 on 2024-05-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default="", upload_to="intruder_image/%Y/%m/%d/"),
            preserve_default=False,
        ),
    ]
